main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name="main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register/", views.register, name="register"),
    #path("activated/", views.activate_account, name="activate"),
    path("register/form/", views.form, name="form"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("account/", views.account_view, name="account_view"),
    path("edit/", views.edit_account, name="edit_account"),
    path("editUsername/", views.edit_Username, name="edit_username"),
    path("editEmail/", views.edit_Email, name="edit_email"),
    path("duyurular/", views.duyurular, name="duyurular"),
    path("premium/", views.premium, name="premium"),
    path("get_premium/", views.get_premium, name="get_premium"),
    path("iletisim/", views.iletisim, name="iletisim"),
    path("yardim/", views.yardim, name="yardim"),
    

    
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name = "main/accounts/password_reset.html"), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(template_name = "main/accounts/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name = "main/accounts/password_reset_confirm.html"), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name = "main/accounts/password_reset_complete.html"), name="password_reset_complete"),

    path("password_change/", auth_views.PasswordChangeView.as_view(template_name="main/accounts/password_change.html"), name="password_change"),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(template_name = "main/accounts/password_change_done.html"), name= "password_change_done"),
    
] 

sinavlar/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name="sinavlar"

urlpatterns = [
    path("sinavlar/", views.sinavlar, name="sinavlar"),
    path("<single_slug>", views.single_slug, name="single_slug"),
    path("yayinlar/<konular_slug>", views.yayinlar, name="yayinlar"),
    path("testler/<test_slug>", views.testler, name="testler"),
    path("sonuclar/", views.sinavlar, name="sonuclar"),
    
    
    
]

sorupunk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('', include('sinavlar.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('django.contrib.auth.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sinavlar/models.py
from django.db import models
from django.utils import timezone



class Kategori(models.Model):
    kategori_title = models.CharField(max_length=200)
    kategori_content = models.TextField()
    kategori_slug = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Kategoriler"


    def __str__(self):
        return self.kategori_title


class Ders(models.Model):
    dersler_title = models.CharField(max_length=200)
    dersler_content = models.TextField()
    dersler_published = models.DateTimeField("Yayınlandığı tarih")
    dersler_kategori = models.ForeignKey(Kategori, default=1, verbose_name="Kategori", on_delete=models.SET_DEFAULT)
    #dersler_image = models.ImageField(upload_to="images", blank=True)
    
    class Meta:
        verbose_name_plural = "Dersler"


    def __str__(self):
         return f"{self.dersler_title} - {self.dersler_kategori}"  
        

class Konu(models.Model):
    konular_title = models.CharField(max_length=200)
    konular_content = models.TextField()
    konular_ders = models.ForeignKey(Ders, default=1, verbose_name="Ders", on_delete=models.SET_DEFAULT)
    konular_published = models.DateTimeField("Yayınlandığı tarih", default=timezone.now())
    konular_slug = models.CharField(max_length=200, default=1)
    
    class Meta:
        verbose_name_plural = "Konular"
    
    def __str__(self):
        return f"{self.konular_title} - {self.konular_ders.dersler_kategori}"

class Yayın(models.Model):
    yayin_title = models.CharField(max_length = 200)
    yayin_slug = models.CharField(max_length = 200)
    
    
    #yayin_logo = models.ImageField(upload_to="images", blank=True)

    class Meta:
        verbose_name_plural = "Yayın"
    
    def __str__(self):
        return self.yayin_title
    


class Test(models.Model):
    test_konu = models.ForeignKey(Konu, default="", verbose_name="Ders", on_delete=models.CASCADE)
    test_yayin = models.ForeignKey(Yayın, default="", verbose_name = "Yayın",  related_name = "yayin", on_delete=models.CASCADE)
    test_buyuk_title = models.CharField(max_length = 200, verbose_name="Genel Başlık")
    test_alt_title = models.CharField(max_length = 200, verbose_name="Alt Başlık")
    test_slug = models.CharField(max_length = 200)
    test_fiyat = models.DecimalField(max_digits=5, decimal_places=2)
    test_published = models.DateTimeField("Yayınlandığı tarih", default=timezone.now())
    test_sayi = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name_plural =  "Testler"

    def __str__(self):
        return  f"{self.test_alt_title} - {self.test_yayin} - {self.test_konu.konular_ders.dersler_kategori}"

class Soru(models.Model):
    soru_test = models.ForeignKey(Test, verbose_name="Test", default="", on_delete=models.CASCADE)
    soru_soru = models.TextField()
    soru_sirasi = models.CharField(max_length = 100, default="Soru ")

    class Meta:
        verbose_name_plural = "Sorular"

    def __str__(self):
        return f"{self.soru_test} - {self.soru_sirasi}"

class Cevap(models.Model):
    cevap_soru = models.ForeignKey(Soru, verbose_name="Soru", default="", on_delete = models.CASCADE)
    cevap_content = models.TextField()
    cevap_position = models.PositiveSmallIntegerField(default=0)
    cevap_correct_anwser = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Cevaplar"
        unique_together = [
            ("cevap_soru", "cevap_content"),
            ("cevap_soru", "cevap_position")
        ]

        ordering = ("cevap_position",)
    def __str__(self):
        return f"{self.cevap_soru} - {self.cevap_content}"




# TO DO LİST:

# Sınavlar-Dersler-Konular 3 lemesini düzelt CHECKED
# Testleri ekle 
# Grafikleri göster (testten gelen sonuca göre)
# Konuyu tamamlamadıysa ya da tamamladıysa pfofilde göster 

sinavlar/views.py
from django.shortcuts import render
from .models import Kategori, Konu, Ders, Yayın, Test, Soru, Cevap
from collections import Counter
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json


# Create your views here.

@login_required(login_url="login")
def single_slug(request, single_slug):
    kategori = [k.kategori_slug for k in Kategori.objects.all()]
    if single_slug in kategori:
        kategori_gelen = Kategori.objects.get(kategori_slug = single_slug)
        kategori_id = kategori_gelen.pk
        matching_dersler = Ders.objects.filter(dersler_kategori__pk=kategori_id)
        # testler_url = {}
        # for t in matching_dersler.all():
        #     matching_testler = Testler.objects.filter(test_ders__pk= t.pk)
        #     #matching_testler = matching_testler.values_list('test_title', flat = True).order_by('id')
        #     matching_testler_slug = matching_testler.earliest('test_published')
        #     testler_url[t] = matching_testler_slug.test_slug

        
        series_url = {}
        for m in matching_dersler.filter(konu__isnull=False):
            deneme = m.dersler_kategori # Türkçe Kategoriye gitti yani KPSS
            part_one = Konu.objects.filter(konular_ders__dersler_kategori__pk=deneme.pk)
            konularr = part_one.filter(konular_ders__pk = m.pk)
            part_two = konularr.earliest('konular_published')
            series_url[m] = part_two.konular_slug
            
        return render(request,
                    "sinavlar/dersler.html",
                    {"konular_slug":series_url,})
    
    konular = [k.konular_slug for k in Konu.objects.all()]
    if single_slug in konular:
        this_konu = Konu.objects.get(konular_slug = single_slug)
        konunun_dersi = this_konu.konular_ders
        dersin_konulariA = Konu.objects.filter(konular_ders__pk = konunun_dersi.pk).order_by("konular_published")
        dersin_konulari = dersin_konulariA.filter(konular_ders__dersler_kategori = konunun_dersi.dersler_kategori)
        konular_idx = list(dersin_konulari).index(this_konu)
        return render(request, 
                      "sinavlar/konular.html",
                      {"konu":  this_konu,
                      "sidebar":    dersin_konulari,
                      "konular_idx":konular_idx})
        return HttpResponse(f"{single_slug} bir konudur")



def sinavlar(request):
    return render(request = request,
                  template_name='sinavlar/sinavlar.html',
                  context = {"kategori":Kategori.objects.all})


def yayinlar(request, konular_slug):
    konu = Konu.objects.get(konular_slug = konular_slug)
    konuDers = konu.konular_ders
    testler = Test.objects.filter(test_buyuk_title= konu.konular_title).filter(test_konu__konular_ders__dersler_kategori__pk = konuDers.dersler_kategori.pk)
    
    yayinlar = {}
    
    for t in testler:
        if t.test_buyuk_title != None or t.test_buyuk_title=="":
            if not t.test_yayin in yayinlar.values():
                yayinlar[t] = t.test_yayin

  
    testsayisi = {}
   
    for t in testler:
        adet = testler.filter(test_yayin_id = t.test_yayin_id)
        if t.test_yayin not in testsayisi:
            testsayisi[t.test_yayin] = adet.count()
    
    
    return render(request, 'sinavlar/yayinlar.html', {"yayinlar":yayinlar, "testsayisi":testsayisi} )




def testler(request, test_slug):
    testler = Test.objects.all()
    testler_1 = Test.objects.get(test_slug = test_slug)
    ders = testler_1.test_konu.konular_ders
    diger_testler = Test.objects.filter(test_buyuk_title = testler_1.test_buyuk_title).filter(test_yayin = testler_1.test_yayin).filter(test_konu__konular_ders__dersler_kategori = ders.dersler_kategori)
    testler_idx = list(diger_testler).index(testler_1)
    sorular = Soru.objects.filter(soru_test__pk = testler_1.pk)
    sorular_cevaplar = {}
    
    for soru in sorular:
        cevaplar = Cevap.objects.filter(cevap_soru__pk = soru.pk)
        sorular_cevaplar[soru] = [c for c in cevaplar]


    

    
    return render(request, 'sinavlar/testler.html', {"testler":testler_1,
                                                     "testler_idx":testler_idx,
                                                     "sidebar":diger_testler,
                                                     "soru_cevaplar":sorular_cevaplar,
                                                     })
    # if request.method == "POST":
    #     request.POST.get('c.cevap_soru')
    #     context = dict()
    #     return render(request, 'sinavlar/sonuclar.html', context)
  

    

templates/sinavlar/dersler.html
{% extends 'main/base.html' %}


{% block content %}
<br><br>

<div class="container">

  {% for ders, url in konular_slug.items %}
  <div class="col s12 m6 l4">

    <div class="card purple accent-4">

      <div class="card-content white-text">

        <span class="card-title">{{ders.dersler_title}}</span>
        <p>{{ders.dersler_content}}</p>
     </div>
     
      <div class="card-action">
        <a href="{{url}}" class="white-text text-lighten-1">KONULARA GİT</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}


<div class="container row">
  {% for ders, partone in part_ones.items %}

      <div class="col s12 m6 l4">
        <div class="card purple accent-4">
              <div class="card-content white-text">
                  <!-- <img src="{{ders.dersler_image.url}}" class="img-responsive" style="width: 100% "> -->
                <span class="card-title">{{ders.dersler_title}}</span>
                <p>{{ders.dersler_content}}</p>
              </div>
              <div class="card-action">
                <a href="{{partone}}" class="white-text text-lighten-1">KONULAR</a>
                <a href="#" class="white-text text-lighten-1">TESTLER</a>
              </div>
          </div>
      </div>
  {% endfor %}
</div>

templates/sinavlar/konular.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12, m8, l8">
            <h3>{{konu.konular_title}}</h3>
            <p style="font-size:70%">Published {{konu.konular_published}}</p>
            {{konu.konular_content|safe}}
        </div>

        

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for konu in sidebar %}
                    {% if forloop.counter0 == konular_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{konu.konular_title}}<br>(şuan buradasanız)</div>
                            <p><a href="{% url 'sinavlar:yayinlar' konular_slug=konu.konular_slug  %}"><button class="btn waves-effect waves-light"  style="background-color:purple; color:white; width: 100%;">TESTLERE GİT !</button></a></p>
                        </li>
                        
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{konu.konular_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="{{konu.konular_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Git</button></a>
                                <a href="{% url 'sinavlar:yayinlar' konular_slug=konu.konular_slug  %}"><button class="btn waves-effect waves-light"  style="background-color:purple; color:white;">Testlere Git</button></a></p>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

   

{% endblock %}

templates/sinavlar/sinavlar.html
{% extends 'main/base.html' %}

{% block content %}


  <div class="container row">
    {% for kat in kategori %}
        <div class="col s12 m6 l6">
            <a href="/{{kat.kategori_slug}}", style="color:black">
                <div class="card hoverable">
                    <div class="card-content purple lighten-5">
                        <div class="card-title">{{kat.kategori_title}}</div>
                        <p>{{kat.kategori_content}}</p>
                        
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
  </div>

  
  {% endblock %}
    
    
   

templates/sinavlar/sonuclar.html
{% extends 'main/base.html' %}


{% block content %}

Test sonucunuz:




{% endblock%}

templates/sinavlar/testler.html
{% extends 'main/base.html' %}


{% block content %}

<div class="card">
    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        {% for test in sidebar %}
            {% if forloop.counter0 == testler_idx %}
                <li class="tab"><a class="active" href="{{test.test_slug}}">{{test.test_alt_title}}</a></li>
            {% else %}

                <li class="tab"><a href="{{test.test_slug}}">{{test.test_alt_title}}</a></li>
            {% endif %}
        {% endfor %}
      </ul>
    </div>
   
<form id ='test' method="POST">
    <div class="card-content grey lighten-4">
            <div id="{{test.test_slug}}">
            {%for soru, cevap in soru_cevaplar.items%}
                <br> <br>
                
                <p style="color: red;"> Problem {{soru.soru_sirasi}} ) </p>
                <br>
                <p>{{soru.soru_soru|safe}}</p>
                <br>
                
                    {% for c in cevap%}
                        
                        <label>
                            <input name="{{c.cevap_soru}}" type="radio" value="{{c.cevap_correct_anwser}}"/><span>{{c.cevap_content|safe}}</span>
                        </label>
                    {% endfor %}

            {% endfor %}
            </div>
            <br>
            
            {% if soru_cevaplar|length > 0 %}
            <input style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit" value="TESTİ BİTİR"></input>
            {% endif %}
        </div>
</form>
    
  </div>

 
<script type="text/javascript"> 
$(document).ready(function(){
   $("#test").on("click", function(){
    var radioValue = $("input[name='{{c.cevap_soru}}']:checked").val();
    console.log(radioValue);
  });
});
</script>


{% endblock%}

templates/sinavlar/yayinlar.html
{% extends 'main/base.html' %}


{% block content %}

<br><br>
<div class="container">
  <h5>Lütfen sorusunu çözmek istediğiniz yayını seçin:</h5>
  <br>
  
  {% for test, yayin in yayinlar.items %}
  <div class="col s12 m6 l4">

    <div class="card purple accent-4">

      <div class="card-content white-text">

        <span class="card-title">{{yayin.yayin_title}}</span>
        <p>Fiyat: {{test.test_fiyat}} ₺</p>
        {% for y, t in testsayisi.items %}
            {% if y.id == yayin.id %}
              <p> Test Sayısı: {{t}}  </p>
            {% endif %}
        {% endfor %}
     </div>
     
      <div class="card-action">
        <a href="{%url 'sinavlar:testler' test_slug=test.test_slug%}" class="white-text text-lighten-1">TESTLERE GİT</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock%}

<!-- asdsad 
  
<br><br>
<div class="container">
  <h5>Lütfen sorusunu çözmek istediğiniz yayını seçin:</h5>
  <br>
  

  {% for test, yayin in yayinlar.items %}
  <div class="col s12 m6 l4">

    <div class="card purple accent-4">

      <div class="card-content white-text">

        <span class="card-title">{{yayin.yayin_title}}</span>
        <p>Fiyat: {{test.test_fiyat}} ₺</p>
        <p>Test Sayısı: </p>
     </div>
     
      <div class="card-action">
        <a href="{%url 'sinavlar:testler' test_slug=test.test_slug%}" class="white-text text-lighten-1">TESTLERE GİT</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


yayinlar_slug=yayin.yayin_slug

-->